# Generated by Django 4.0 on 2022-02-12 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_dislikes_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dislikes',
            new_name='down_votes',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='up_votes',
        ),
    ]
