# Generated by Django 4.0 on 2022-04-20 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('flag', models.BooleanField(default=False)),
                ('up_votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='question.question')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('flag', models.BooleanField(default=False)),
                ('up_votes', models.IntegerField(default=0)),
                ('answer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='question.answer')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='auth.user')),
            ],
        ),
    ]
