# Generated by Django 4.0 on 2022-05-30 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_questioncomment_answercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answercomment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='question.question'),
        ),
        migrations.AlterField(
            model_name='answercomment',
            name='answer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='question.answer'),
        ),
        migrations.AlterField(
            model_name='questioncomment',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='question.question'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
