# Generated by Django 4.0 on 2022-02-17 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_post_views'),
        ('question', '0003_alter_answer_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='post.post'),
        ),
    ]
