# Generated by Django 4.0 on 2022-06-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_answer_is_deleted_answercomment_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='notify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='notify',
            field=models.BooleanField(default=False),
        ),
    ]
