# Generated by Django 4.0 on 2022-06-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_answer_notify_question_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncomment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
